inherit_mode:
  merge:
    - Exclude
AllCops:
  NewCops: enable
  Exclude:
    - */example.rb
    - */stack.rb

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false